package graph

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

type Client struct {
	tenantID     string
	clientID     string
	clientSecret string
	http         *http.Client

	// Endpoints are fields rather than constants so tests can point them at a
	// local server. Without this the whole client was untestable without
	// network access, which is how an unescaped space in $orderby shipped.
	tokenEndpoint string // full URL; defaults to the Entra v2 token endpoint
	graphBase     string // scheme+host, no trailing slash
}

// sameAddress compares two mail addresses for identity.
//
// Case-insensitive on the whole address: the local part is technically
// case-sensitive per RFC 5321, but no mail system anybody runs treats it that
// way, and the cost of being pedantic here is failing to recognise our own
// digest because Exchange capitalised it differently in one place.
func sameAddress(a, b string) bool {
	a, b = strings.TrimSpace(a), strings.TrimSpace(b)
	return a != "" && strings.EqualFold(a, b)
}

// SelfHeader marks mail this fleet sent. Graph requires custom header names
// to start with "X-".
//
// Its value is the sending mailbox, so a shared tenant running two fleets can
// tell whose report it is looking at rather than discarding both.
const SelfHeader = "X-CTI-Agent-Sent"

// Graph returns header names in whatever case the sender used, so the match
// is done lowercased. Precomputed rather than lowercased inside the loop.
var selfHeaderLower = strings.ToLower(SelfHeader)

type Message struct {
	ID               string    `json:"id"`
	Subject          string    `json:"subject"`
	ReceivedDateTime time.Time `json:"receivedDateTime"`
	From             string
	BodyText         string

	// SelfSent is true when this message carries SelfHeader - that is, when
	// the fleet sent it. See the comment in SendMail for the loop this closes.
	SelfSent bool

	// AutoSubmitted and AutoResponseSuppress carry the RFC 3834 and Microsoft
	// headers that mark a message as machine-generated.
	//
	// Headers, not subject text. These decide whether a message is eligible to
	// be moved to Deleted Items, so precision matters more than recall: an
	// auto-reply that omits the headers stays in the inbox, which is a tidiness
	// problem, whereas a real advisory matched by a subject pattern would be
	// deleted, which is not.
	AutoSubmitted        string
	AutoResponseSuppress string
}

// IsAutoReply reports whether the sending system declared this an automatic
// reply.
//
// RFC 3834 reserves "auto-replied" for vacation notices and the like, and
// explicitly distinguishes it from "auto-generated" (a report or notification),
// which we do NOT treat as an auto-reply - a vendor advisory generated by a
// mailing system is auto-generated and must never be deleted.
func (m Message) IsAutoReply() bool {
	switch strings.ToLower(strings.TrimSpace(m.AutoSubmitted)) {
	case "auto-replied", "auto-notified":
		return true
	}
	// Exchange sets this on out-of-office replies. "All" is what an OOF
	// template sends; the presence of the header alone is not enough, since
	// other automated mail sets it to suppress further responses.
	if strings.EqualFold(strings.TrimSpace(m.AutoResponseSuppress), "All") &&
		strings.Contains(strings.ToLower(m.AutoSubmitted), "auto") {
		return true
	}
	return false
}

type tokenResponse struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
	ExpiresIn   int    `json:"expires_in"`
}

type messagesResponse struct {
	Value []struct {
		ID               string    `json:"id"`
		Subject          string    `json:"subject"`
		ReceivedDateTime time.Time `json:"receivedDateTime"`
		From             struct {
			EmailAddress struct {
				Name    string `json:"name"`
				Address string `json:"address"`
			} `json:"emailAddress"`
		} `json:"from"`
		Body struct {
			ContentType string `json:"contentType"`
			Content     string `json:"content"`
		} `json:"body"`
		InternetMessageHeaders []struct {
			Name  string `json:"name"`
			Value string `json:"value"`
		} `json:"internetMessageHeaders"`
	} `json:"value"`
	NextLink string `json:"@odata.nextLink"`
}

func New(tenantID, clientID, clientSecret string) *Client {
	return &Client{
		tenantID:     tenantID,
		clientID:     clientID,
		clientSecret: clientSecret,
		http:         &http.Client{Timeout: 60 * time.Second},
		tokenEndpoint: fmt.Sprintf(
			"https://login.microsoftonline.com/%s/oauth2/v2.0/token", tenantID),
		graphBase: "https://graph.microsoft.com/v1.0",
	}
}

// AccessToken returns a client-credentials token for Graph.
//
// Exported for `cti-mailer --check`, which decodes the token's claims to
// report which application roles the tenant actually consented to. That is the
// one question no amount of local configuration can answer, and the step
// people skip - a permission added in Entra without admin consent looks
// identical to one that was never added.
//
// Callers must not log the token. It is a bearer credential for the whole
// mailbox.
func (c *Client) AccessToken(ctx context.Context) (string, error) {
	return c.token(ctx)
}

func (c *Client) token(ctx context.Context) (string, error) {
	endpoint := c.tokenEndpoint
	form := url.Values{}
	form.Set("client_id", c.clientID)
	form.Set("client_secret", c.clientSecret)
	form.Set("scope", "https://graph.microsoft.com/.default")
	form.Set("grant_type", "client_credentials")

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := c.http.Do(req)
	if err != nil {
		return "", err
	}
	defer func() {
		_ = resp.Body.Close()
	}()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read graph token response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return "", fmt.Errorf("graph token request failed: HTTP %d: %s", resp.StatusCode, string(body))
	}

	var tr tokenResponse
	if err := json.Unmarshal(body, &tr); err != nil {
		return "", err
	}
	if tr.AccessToken == "" {
		return "", fmt.Errorf("graph token response did not include access_token")
	}
	return tr.AccessToken, nil
}

// messagesURL builds the first-page request URL for a mailbox folder.
//
// Extracted so it can be tested without a network call. It exists because an
// unescaped space in $orderby shipped once: every OData *value* must be
// escaped, or the space lands in the HTTP request line and the edge rejects
// the request with an HTML "Bad Request" page before Graph's API layer sees
// it. That failure does not look like a Graph error, so it costs real time.
//
// The "$" prefixes stay literal rather than going through
// url.Values.Encode(), which would percent-encode them to %24. Graph accepts
// %24, but literal "$" matches its documentation and error messages, which
// keeps these URLs greppable against the docs.
func messagesURL(mailbox, folder string, since time.Time) string {
	return messagesURLBase("https://graph.microsoft.com/v1.0", mailbox, folder, since)
}

func messagesURLBase(base, mailbox, folder string, since time.Time) string {
	filter := fmt.Sprintf("receivedDateTime ge %s", since.UTC().Format(time.RFC3339))
	// internetMessageHeaders is requested so the mailbox cleanup lane can tell
	// an out-of-office auto-reply from a real advisory by what the sending
	// system declared, rather than by guessing from the subject. Graph returns
	// the full header set for a $select that names it.
	selectFields := "id,subject,receivedDateTime,from,body,internetMessageHeaders"

	params := []string{
		"$top=50",
		"$select=" + url.QueryEscape(selectFields),
		"$orderby=" + url.QueryEscape("receivedDateTime desc"),
		"$filter=" + url.QueryEscape(filter),
	}
	return fmt.Sprintf("%s/users/%s/mailFolders/%s/messages?%s",
		base,
		url.PathEscape(mailbox),
		url.PathEscape(folder),
		strings.Join(params, "&"),
	)
}

// graphError turns a failed response into something actionable.
//
// Graph reports its own errors as JSON. An HTML body means the request never
// reached Graph - it was rejected by the edge for being malformed - so saying
// so directly saves a long detour through permissions and mailbox settings
// that are not the problem.
func graphError(status int, body []byte, endpoint string) error {
	trimmed := strings.TrimSpace(string(body))

	if strings.HasPrefix(trimmed, "<") {
		return fmt.Errorf("graph request was rejected before reaching the API "+
			"(HTTP %d, HTML response). This means a malformed URL, almost always "+
			"an unescaped character in an OData query parameter such as a space "+
			"in $orderby or $filter.\nrequest: %s",
			status, endpoint)
	}

	var ge struct {
		Error struct {
			Code    string `json:"code"`
			Message string `json:"message"`
		} `json:"error"`
	}
	if err := json.Unmarshal(body, &ge); err == nil && ge.Error.Code != "" {
		hint := ""
		switch ge.Error.Code {
		case "ErrorAccessDenied", "Authorization_RequestDenied", "ErrorItemNotFound":
			hint = "\nhint: check that Mail.Read is granted as an APPLICATION " +
				"permission with admin consent, and that any Application Access " +
				"Policy includes this mailbox."
		case "ResourceNotFound", "ErrorInvalidUser", "MailboxNotEnabledForRESTAPI":
			hint = "\nhint: check GRAPH_MAILBOX is a real, licensed mailbox, and " +
				"that GRAPH_FOLDER names an existing folder."
		case "ErrorInvalidProperty", "BadRequest":
			hint = "\nhint: the OData query was understood but rejected - check " +
				"$select field names and the $filter datetime format."
		}
		return fmt.Errorf("graph messages request failed: HTTP %d %s: %s%s",
			status, ge.Error.Code, ge.Error.Message, hint)
	}

	if len(trimmed) > 800 {
		trimmed = trimmed[:800] + "..."
	}
	return fmt.Errorf("graph messages request failed: HTTP %d: %s", status, trimmed)
}

func (c *Client) RecentMessages(ctx context.Context, mailbox, folder string, since time.Time) ([]Message, error) {
	tok, err := c.token(ctx)
	if err != nil {
		return nil, err
	}

	endpoint := messagesURLBase(c.graphBase, mailbox, folder, since)

	var all []Message
	for endpoint != "" {
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
		if err != nil {
			return nil, err
		}
		req.Header.Set("Authorization", "Bearer "+tok)
		req.Header.Set("Prefer", `outlook.body-content-type="text"`)

		resp, err := c.http.Do(req)
		if err != nil {
			return nil, err
		}
		body, readErr := io.ReadAll(resp.Body)
		closeErr := resp.Body.Close()
		if readErr != nil {
			return nil, fmt.Errorf("failed to read graph messages response: %w", readErr)
		}
		if closeErr != nil {
			return nil, fmt.Errorf("failed to close graph messages response body: %w", closeErr)
		}
		if resp.StatusCode < 200 || resp.StatusCode > 299 {
			return nil, graphError(resp.StatusCode, body, endpoint)
		}

		var mr messagesResponse
		if err := json.Unmarshal(body, &mr); err != nil {
			return nil, err
		}
		for _, m := range mr.Value {
			from := strings.TrimSpace(m.From.EmailAddress.Address)
			if m.From.EmailAddress.Name != "" {
				from = fmt.Sprintf("%s <%s>", m.From.EmailAddress.Name, m.From.EmailAddress.Address)
			}
			msg := Message{
				ID:               m.ID,
				Subject:          m.Subject,
				ReceivedDateTime: m.ReceivedDateTime,
				From:             from,
				BodyText:         m.Body.Content,
			}
			for _, h := range m.InternetMessageHeaders {
				switch strings.ToLower(strings.TrimSpace(h.Name)) {
				case "auto-submitted":
					msg.AutoSubmitted = h.Value
				case "x-auto-response-suppress":
					msg.AutoResponseSuppress = h.Value
				case selfHeaderLower:
					msg.SelfSent = true
				}
			}
			// Mail we sent before SelfHeader existed carries no header, so the
			// sender is the backstop. The fleet sends AS this mailbox, so mail
			// from it to itself is our own report coming back round.
			if !msg.SelfSent && sameAddress(m.From.EmailAddress.Address, mailbox) {
				msg.SelfSent = true
			}
			all = append(all, msg)
		}
		endpoint = mr.NextLink
	}
	return all, nil
}

// ── sending ─────────────────────────────────────────────────────────────────

// SendMailRequest is one outbound message.
type SendMailRequest struct {
	From    string   // the mailbox to send AS; needs Mail.Send on the app
	To      []string // recipients
	CC      []string // copied recipients; subject to the caller's allowlist too
	Subject string
	HTML    string // body, contentType HTML
	// HighImportance flags the message. Reserved for genuine Sev5 alerts: a
	// system that marks everything urgent has marked nothing urgent.
	HighImportance bool

	// Attachments are inlined into the sendMail payload as base64, which is
	// what Graph accepts for anything under its size limit. The caller decides
	// what is small enough; this package does not silently drop one.
	Attachments []Attachment

	// SaveToSentItems is a pointer so that nil means true - the behaviour
	// every existing caller already relies on. A plain bool would make the
	// zero value "do not save", silently changing what cti-alert does the
	// moment this field was added.
	SaveToSentItems *bool
}

// Attachment is one file inlined into a message.
type Attachment struct {
	Name        string
	ContentType string
	Bytes       []byte
}

type sendMailPayload struct {
	Message struct {
		Subject string `json:"subject"`
		Body    struct {
			ContentType string `json:"contentType"`
			Content     string `json:"content"`
		} `json:"body"`
		ToRecipients []recipient      `json:"toRecipients"`
		CCRecipients []recipient      `json:"ccRecipients,omitempty"`
		Importance   string           `json:"importance"`
		Attachments  []fileAttachment `json:"attachments,omitempty"`

		// Headers we set on our own outgoing mail. Graph requires custom
		// header names to begin with "X-".
		Headers []messageHeader `json:"internetMessageHeaders,omitempty"`
	} `json:"message"`
	SaveToSentItems bool `json:"saveToSentItems"`
}

type messageHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// fileAttachment is Graph's inline attachment shape. The @odata.type is
// required and the API rejects the message without it.
type fileAttachment struct {
	ODataType    string `json:"@odata.type"`
	Name         string `json:"name"`
	ContentType  string `json:"contentType"`
	ContentBytes string `json:"contentBytes"`
}

type recipient struct {
	EmailAddress struct {
		Address string `json:"address"`
	} `json:"emailAddress"`
}

// SendMail sends one message as the given mailbox via Graph sendMail.
//
// This reuses the same app registration and token path the mailbox reader
// uses, so the only extra requirement is the Mail.Send application permission
// with admin consent.
//
// It returns the Graph request-id on success. sendMail answers 202 with an
// empty body, so there is no message id to report - request-id is what
// Microsoft support asks for when a message goes missing.
// SendMailResult is what the send actually returned.
//
// The status code is here because the caller logs it and mailer.py logged the
// real one. Hardcoding 202 - the code Graph returns today - would be a report
// of what we expected rather than what happened, which is the distinction this
// codebase keeps having to relearn.
type SendMailResult struct {
	RequestID string
	Status    int
}

func (c *Client) SendMail(ctx context.Context, req SendMailRequest) (SendMailResult, error) {
	if req.From == "" {
		return SendMailResult{}, fmt.Errorf("SendMail: From is required (the sending mailbox)")
	}
	if len(req.To) == 0 {
		// No default recipient, deliberately. A hardcoded address is a
		// mis-send waiting to happen on someone else's tenant.
		return SendMailResult{}, fmt.Errorf("SendMail: at least one recipient is required")
	}
	if req.Subject == "" {
		return SendMailResult{}, fmt.Errorf("SendMail: Subject is required")
	}

	tok, err := c.token(ctx)
	if err != nil {
		return SendMailResult{}, err
	}

	var p sendMailPayload
	p.Message.Subject = req.Subject
	p.Message.Body.ContentType = "HTML"
	p.Message.Body.Content = req.HTML
	p.Message.Importance = "normal"
	if req.HighImportance {
		p.Message.Importance = "high"
	}
	for _, addr := range req.To {
		var r recipient
		r.EmailAddress.Address = addr
		p.Message.ToRecipients = append(p.Message.ToRecipients, r)
	}
	for _, addr := range req.CC {
		var r recipient
		r.EmailAddress.Address = addr
		p.Message.CCRecipients = append(p.Message.CCRecipients, r)
	}
	for _, a := range req.Attachments {
		ct := a.ContentType
		if ct == "" {
			ct = "application/octet-stream"
		}
		p.Message.Attachments = append(p.Message.Attachments, fileAttachment{
			ODataType:    "#microsoft.graph.fileAttachment",
			Name:         a.Name,
			ContentType:  ct,
			ContentBytes: base64.StdEncoding.EncodeToString(a.Bytes),
		})
	}
	// Stamp our own mail so the ingest can recognise it later.
	//
	// THE LOOP THIS CLOSES
	//
	// The digest is sent TO the same mailbox the digest READS. So yesterday's
	// digest arrives as today's input, the extractor pulls the CVEs out of our
	// own report, and they are presented as newly mentioned - every day,
	// forever. Observed 2026-10-04: "EMAILS READ THIS RUN - 2 total, 1
	// mentioning a CVE", and the one mentioning a CVE was the previous day's
	// own digest.
	//
	// It is self-sustaining. A CVE reported once stays in the mailbox as our
	// own mail and re-enters every subsequent run, so the daily can never go
	// quiet and the counts are fiction. Worse, nothing about it looks wrong:
	// the email is well-formed, the CVE is real, and the pipeline is working
	// exactly as written.
	//
	// A header rather than a sender check, because a header is something we
	// control and can assert in a test. The sender check in RecentMessages is
	// the backstop for mail already sitting in the mailbox from before this
	// existed.
	p.Message.Headers = append(p.Message.Headers, messageHeader{
		Name: SelfHeader, Value: req.From,
	})

	p.SaveToSentItems = true
	if req.SaveToSentItems != nil {
		p.SaveToSentItems = *req.SaveToSentItems
	}

	body, err := json.Marshal(p)
	if err != nil {
		return SendMailResult{}, err
	}

	endpoint := fmt.Sprintf("%s/users/%s/sendMail",
		c.graphBase, url.PathEscape(req.From))
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint,
		strings.NewReader(string(body)))
	if err != nil {
		return SendMailResult{}, err
	}
	httpReq.Header.Set("Authorization", "Bearer "+tok)
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(httpReq)
	if err != nil {
		return SendMailResult{}, err
	}
	defer func() { _ = resp.Body.Close() }()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return SendMailResult{}, fmt.Errorf("failed to read sendMail response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return SendMailResult{}, sendMailError(resp.StatusCode, respBody, req.From)
	}

	reqID := resp.Header.Get("request-id")
	if reqID == "" {
		reqID = resp.Header.Get("client-request-id")
	}
	return SendMailResult{RequestID: reqID, Status: resp.StatusCode}, nil
}

// sendMailError annotates the failures that actually happen in practice,
// because "403 Forbidden" on its own sends people to the wrong place.
func sendMailError(status int, body []byte, mailbox string) error {
	trimmed := strings.TrimSpace(string(body))
	if len(trimmed) > 600 {
		trimmed = trimmed[:600] + "..."
	}
	switch {
	case status == 403 && strings.Contains(trimmed, "MailboxNotEnabledForRESTAPI"):
		return fmt.Errorf("sendMail 403: %s is not a REST-enabled mailbox "+
			"(shared mailboxes need a license, or it is on-prem): %s", mailbox, trimmed)
	case status == 403:
		return fmt.Errorf("sendMail 403: the app registration is probably missing "+
			"Mail.Send as an APPLICATION permission, or admin consent was never "+
			"granted, or an Application Access Policy excludes %s: %s", mailbox, trimmed)
	case status == 404:
		return fmt.Errorf("sendMail 404: mailbox %s not found - check the address "+
			"and that it is a real mailbox, not a distribution group: %s", mailbox, trimmed)
	default:
		return fmt.Errorf("sendMail failed: HTTP %d: %s", status, trimmed)
	}
}

// Folder is a destination this client is willing to move a message to.
//
// A closed set, not a string parameter, and it contains no way to express a
// permanent deletion. Moving to DeletedItems is the equivalent of pressing
// Delete in Outlook: the message sits in Deleted Items, then in Recoverable
// Items, and can be brought back. Graph's DELETE /messages/{id} and the
// purge endpoints are deliberately not implemented here - an automated lane
// that runs unattended every day should not have the vocabulary to destroy
// mail, and "we can add it later if needed" is how it ends up available at
// 3am to something that misidentified a message.
type Folder string

const (
	FolderArchive      Folder = "archive"
	FolderDeletedItems Folder = "deleteditems"
)

// MoveMessage moves one message to a well-known folder and returns the new
// message ID.
//
// Graph's move is a copy-then-delete, so the ID changes. The new ID is
// returned because the caller records what it did, and a record pointing at an
// ID that no longer resolves cannot be checked afterwards.
func (c *Client) MoveMessage(ctx context.Context, mailbox, messageID string, dest Folder) (string, error) {
	switch dest {
	case FolderArchive, FolderDeletedItems:
	default:
		return "", fmt.Errorf("MoveMessage: refusing unknown destination %q", dest)
	}
	if strings.TrimSpace(mailbox) == "" || strings.TrimSpace(messageID) == "" {
		return "", fmt.Errorf("MoveMessage: mailbox and messageID are both required")
	}

	tok, err := c.token(ctx)
	if err != nil {
		return "", err
	}
	endpoint := fmt.Sprintf("%s/users/%s/messages/%s/move",
		c.graphBase, url.PathEscape(mailbox), url.PathEscape(messageID))
	payload, err := json.Marshal(map[string]string{"destinationId": string(dest)})
	if err != nil {
		return "", err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(payload))
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+tok)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("MoveMessage: reading response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return "", moveError(resp.StatusCode, body, mailbox, dest)
	}
	var moved struct {
		ID string `json:"id"`
	}
	// A 2xx with an unparseable body still means the move happened, so this is
	// not an error - the caller just cannot record the new ID.
	_ = json.Unmarshal(body, &moved)
	return moved.ID, nil
}

// moveError names the failure that will actually happen: the new permission
// not being granted.
func moveError(status int, body []byte, mailbox string, dest Folder) error {
	trimmed := strings.TrimSpace(string(body))
	if len(trimmed) > 600 {
		trimmed = trimmed[:600] + "..."
	}
	// Tagged switch: every case here is a plain status comparison, unlike
	// sendMailError above, which pairs a status with a body check and so has
	// to stay untagged.
	switch status {
	case http.StatusForbidden:
		return fmt.Errorf("move to %s 403: the app registration needs Mail.ReadWrite "+
			"as an APPLICATION permission with admin consent granted - Mail.Read is "+
			"not enough to move a message - or an Application Access Policy excludes "+
			"%s: %s", dest, mailbox, trimmed)
	case http.StatusNotFound:
		return fmt.Errorf("move to %s 404: message not found in %s. It may already "+
			"have been moved, by this lane or by a person: %s", dest, mailbox, trimmed)
	default:
		return fmt.Errorf("move to %s failed: HTTP %d: %s", dest, status, trimmed)
	}
}
