// Package qualys parses Qualys WAS (TotalAppSec) scan-completion
// notifications and, when credentials allow, fetches per-finding detail.
//
// The notification is generated by Qualys from a fixed template, so this keys
// on the label text — "Scan Status :", "Authentication Record :" — rather than
// on the HTML structure, which carries no stable classes or ids and is laid
// out with bare <div> and <br>. Labels are what a human reads and are the part
// least likely to change silently; when they do change, the parse comes back
// with problems rather than with wrong numbers.
package qualys

import (
	"fmt"
	"html"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/zany2dmax/cti-agent/internal/appscan"
)

// Provider parses Qualys WAS notifications.
type Provider struct{}

// Name is the stable key recorded on every result.
func (Provider) Name() string { return "qualys-was" }

// Recognises matches the sender and subject Qualys actually uses.
//
// Both, not either. The subject alone would match a human forwarding one of
// these into the mailbox with commentary attached, and the body of a forward
// is not the body this parser expects.
func (Provider) Recognises(sender, subject string) bool {
	s := strings.ToLower(sender)
	if !strings.Contains(s, "@qualys.net") && !strings.Contains(s, "@qualys.com") {
		return false
	}
	return strings.Contains(strings.ToLower(subject),
		"web application vulnerability scan results")
}

var (
	tagRE  = regexp.MustCompile(`(?s)<[^>]*>`)
	brRE   = regexp.MustCompile(`(?i)<br\s*/?>|</(p|div|tr|td|th|h[1-6]|li)>`)
	dropRE = regexp.MustCompile(`(?is)<style[^>]*>.*?</style>` +
		`|<script[^>]*>.*?</script>` +
		`|<head[^>]*>.*?</head>`) // RE2: no backreferences, so spelled out
	hiddenRE    = regexp.MustCompile(`(?is)<div[^>]*(?:display:none|visibility:hidden)[^>]*>.*?</div>`)
	pfptRE      = regexp.MustCompile(`(?is)<div[^>]+id=["']?pfptBanner[^>]*>.*?</div>`)
	reportRE    = regexp.MustCompile(`(?is)view these scan results[^<]*<a[^>]+href\s*=\s*["']([^"']+)["']`)
	sevLineRE   = regexp.MustCompile(`^Severity\s+([1-5])\s+"[^"]*"\s*:\s*(-?\d+)(?:\s*\(\s*([-+=]?\s*\d*)\s*\))?(.*)$`)
	lifeRE      = regexp.MustCompile(`(\d+)\s+(New|Reopened|Active|Fixed|Ignored)`)
	crawledRE   = regexp.MustCompile(`^Links Crawled\s*:\s*(\d+)`)
	runSuffixRE = regexp.MustCompile(`\s+(?:Bimonthly\s+|Monthly\s+|Weekly\s+)?Run\s*#\s*\d+\s*$`)
)

// Section headings in the body, in the order Qualys emits them.
const (
	secScanVulns = "Summary of Vulnerabilities"
	secScanSens  = "Summary of Sensitive Contents"
	secScanInfo  = "Summary of Information Gathered"
	secAppVulns  = "Vulnerabilities (New, Reopened, Active, Fixed, Ignored)"
	secAppSens   = "Sensitive Contents (New, Reopened, Active, Fixed, Ignored)"
)

// Parse reads one notification body.
func (p Provider) Parse(body string) (appscan.ScanResult, []string) {
	r := appscan.ScanResult{Provider: p.Name()}
	var problems []string

	// The link comes out of the raw HTML before tags are stripped, and is
	// verified before it is kept. These arrive at a published address, and a
	// forged scan notification carrying a link somewhere else is cheap.
	if m := reportRE.FindStringSubmatch(body); m != nil {
		if u, err := UnwrapReportLink(html.UnescapeString(m[1])); err == nil {
			r.ReportURL = u
		} else {
			r.LinkProblem = err.Error()
			problems = append(problems, "the scan report link did not resolve to "+
				"a Qualys host: "+err.Error())
		}
	} else {
		// Every real notification carries this. Its absence means the template
		// changed, which is worth saying out loud rather than quietly losing
		// the one link that leads to the actual findings.
		problems = append(problems, "no scan report link found in the notification")
	}

	lines := textLines(body)
	field := func(label string) string { return fieldValue(lines, label) }

	r.ScanTitle = field("Scan Title")
	// The application's name is the Target line - a real notification reads
	// "Target : <web app name>" - and the title only as a fallback. The title
	// is a run name ("<something> Bimonthly Run #47") that on the real estate
	// rarely matched the application's actual name, which is what the finding
	// search is keyed on when no application id is available.
	r.App = appFromTitle(r.ScanTitle)
	r.Reference = field("Scan Reference")
	r.Target = field("Target")
	if t := tidy(r.Target); t != "" {
		r.App = t
	}
	r.LinksCrawled = atoiOr(firstMatch(lines, crawledRE), 0)

	r.Auth = appscan.Auth{
		Record: notNone(field("Authentication Record")),
		Status: field("Authentication Status"),
	}

	r.Status = field("Scan Status")
	// "Finished : OK" is the healthy value. Anything else - cancelled, time
	// limit exceeded, finished with errors - produced a partial crawl, and its
	// counts describe a measurement that was never completed.
	r.Complete = strings.Contains(strings.ToLower(r.Status), "finished") &&
		strings.Contains(strings.ToUpper(r.Status), "OK")

	r.Started = parseQualysTime(field("Start Date"))
	r.Finished = parseQualysTime(field("End Date"))

	r.ScanCounts, r.ScanDelta = scanCounts(lines, secScanVulns, secScanSens)
	r.AppState = lifecycle(lines, secAppVulns, secAppSens)

	// Checks, not assumptions. Each of these has a specific way of being
	// wrong that would otherwise read as a real number.
	if r.ScanTitle == "" {
		problems = append(problems, "could not find the scan title")
	}
	if r.Reference == "" {
		problems = append(problems, "could not find the scan reference - "+
			"without it the same notification cannot be deduplicated")
	}
	if r.Status == "" {
		problems = append(problems, "could not find the scan status, so it is "+
			"not known whether this scan completed")
	}
	if r.Auth.Status == "" {
		problems = append(problems, "could not find the authentication status - "+
			"treat the counts as an unauthenticated scan until this is fixed")
	}
	if stated := statedTotal(lines, secScanVulns); stated >= 0 && stated != r.ScanCounts.Total() {
		problems = append(problems, fmt.Sprintf(
			"the per-scan severity lines sum to %d but the email states a total "+
				"of %d - a severity line was missed",
			r.ScanCounts.Total(), stated))
	}
	return r, problems
}

// textLines reduces the HTML to the lines a reader would see.
func textLines(body string) []string {
	s := dropRE.ReplaceAllString(body, " ")
	s = hiddenRE.ReplaceAllString(s, " ") // preheader copies of the summary
	s = pfptRE.ReplaceAllString(s, " ")   // the external-sender banner
	s = brRE.ReplaceAllString(s, "\n")
	s = tagRE.ReplaceAllString(s, " ")
	s = html.UnescapeString(s)
	s = strings.NewReplacer("\u200b", "", "\u00a0", " ", "\ufeff", "").Replace(s)

	var out []string
	for _, l := range strings.Split(s, "\n") {
		if l = strings.Join(strings.Fields(l), " "); l != "" {
			out = append(out, l)
		}
	}
	return out
}

// fieldValue returns the text after "Label :" on whichever line carries it.
func fieldValue(lines []string, label string) string {
	pre := strings.ToLower(label) + " :"
	for _, l := range lines {
		low := strings.ToLower(l)
		if i := strings.Index(low, pre); i >= 0 {
			return strings.TrimSpace(l[i+len(pre):])
		}
	}
	return ""
}

// scanCounts reads the per-scan severity table and its deltas.
//
// Bounded to the section between its own heading and the next one. Without
// that bound the parser reads whichever "Severity 5" line comes first and
// silently returns the Sensitive Contents or Information Gathered figures,
// which are different and almost always zero - a clean-looking wrong answer.
func scanCounts(lines []string, from, to string) (counts, delta appscan.Counts) {
	for _, l := range section(lines, from, to) {
		m := sevLineRE.FindStringSubmatch(l)
		if m == nil {
			continue
		}
		sev, _ := strconv.Atoi(m[1])
		set(&counts, sev, atoiOr(m[2], 0))
		if d := strings.ReplaceAll(m[3], " ", ""); d != "" && d != "=" {
			set(&delta, sev, atoiOr(d, 0))
		}
	}
	return counts, delta
}

// lifecycle reads the application-level table, where each severity line
// carries five sub-counts.
func lifecycle(lines []string, from, to string) appscan.Lifecycle {
	var lc appscan.Lifecycle
	for _, l := range section(lines, from, to) {
		m := sevLineRE.FindStringSubmatch(l)
		if m == nil {
			continue
		}
		sev, _ := strconv.Atoi(m[1])
		set(&lc.Total, sev, atoiOr(m[2], 0))
		for _, sub := range lifeRE.FindAllStringSubmatch(l, -1) {
			n := atoiOr(sub[1], 0)
			switch sub[2] {
			case "New":
				set(&lc.New, sev, n)
			case "Reopened":
				set(&lc.Reopened, sev, n)
			case "Active":
				set(&lc.Active, sev, n)
			case "Fixed":
				set(&lc.Fixed, sev, n)
			case "Ignored":
				set(&lc.Ignored, sev, n)
			}
		}
	}
	return lc
}

// section returns the lines between two headings. An absent end heading means
// "to the end", which is correct for the last section in the mail.
func section(lines []string, from, to string) []string {
	start := -1
	for i, l := range lines {
		if strings.Contains(l, from) {
			start = i + 1
			break
		}
	}
	if start < 0 {
		return nil
	}
	for i := start; i < len(lines); i++ {
		if strings.Contains(lines[i], to) {
			return lines[start:i]
		}
	}
	return lines[start:]
}

// statedTotal is the "Total : N" line Qualys prints under a section, or -1.
func statedTotal(lines []string, from string) int {
	for _, l := range section(lines, from, "Summary of Sensitive") {
		if strings.HasPrefix(l, "Total :") {
			f := strings.Fields(strings.TrimPrefix(l, "Total :"))
			if len(f) > 0 {
				return atoiOr(f[0], -1)
			}
		}
	}
	return -1
}

func set(c *appscan.Counts, sev, n int) {
	switch sev {
	case 5:
		c.Urgent = n
	case 4:
		c.Crit = n
	case 3:
		c.Serious = n
	case 2:
		c.Medium = n
	case 1:
		c.Minimal = n
	}
}

// appFromTitle strips the run suffix: "Example App Run #48" -> "Example App".
//
// The application is what a reader tracks across weeks; the run number is
// bookkeeping. Keeping them joined would make every scan look like a new
// application.
func appFromTitle(title string) string {
	return strings.TrimSpace(runSuffixRE.ReplaceAllString(title, ""))
}

// notNone treats Qualys's literal "None" as absent.
//
// Without this an unauthenticated scan reports an authentication record of
// "None", which is a non-empty string and would read as configured to any
// caller checking for one.
func notNone(s string) string {
	if strings.EqualFold(strings.TrimSpace(s), "none") {
		return ""
	}
	return strings.TrimSpace(s)
}

// parseQualysTime reads "10/04/2026 at 00:02:43 (GMT +0000)".
//
// An unreadable timestamp is left zero rather than guessed; the caller falls
// back to the message's received time, which is at least true about something.
func parseQualysTime(s string) time.Time {
	s = strings.TrimSpace(s)
	if i := strings.Index(s, "("); i >= 0 {
		s = strings.TrimSpace(s[:i])
	}
	s = strings.Replace(s, " at ", " ", 1)
	for _, layout := range []string{"01/02/2006 15:04:05", "01/02/2006 15:04"} {
		if t, err := time.Parse(layout, s); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

func firstMatch(lines []string, re *regexp.Regexp) string {
	for _, l := range lines {
		if m := re.FindStringSubmatch(l); m != nil {
			return m[1]
		}
	}
	return ""
}

func atoiOr(s string, def int) int {
	n, err := strconv.Atoi(strings.TrimSpace(strings.TrimPrefix(s, "+")))
	if err != nil {
		return def
	}
	return n
}
